---
- name: Install a new version of the KDC server
  yum: name="{{ item }}" state=latest update_cache=yes
  when: ansible_facts['os_family'] == "RedHat"
  loop: 
    - krb5-server
    - krb5-libs
    - krb5-workstation
- template: 
    src: templates/krb5.conf.j2
    dest: /etc/krb5.conf
    mode: 0755
- stat: path=/var/kerberos/krb5kdc/principal    
  register: kdc_db
- name: Create kerberos database
  expect:
    command: kdb5_util create -s
    responses:
      database master key: "{{ db_master_key }}"
      database master key to verify: "{{ db_master_key }}"
  when: not kdc_db.stat.exists and ansible_facts['os_family'] == "RedHat"  
- name: Start the KDC server and the KDC admin server
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"  
  loop:
    - krb5kdc
    - kadmin
- name: Create a Kerberos Admin
  expect:
    command: kadmin.local -q "addprinc admin/admin"
    responses:
      Enter password for principal: "{{ admin_princ_pswd }}"
      Re-enter password for principal: "{{ admin_princ_pswd }}"
  when: ansible_facts['os_family'] == "RedHat" 
- name: ensure that kdc acl file includes the realm
  shell: sed -i '1,$s/EXAMPLE.COM/{{realm}}/g' /var/kerberos/krb5kdc/kadm5.acl
  when: ansible_facts['os_family'] == "RedHat" 
- name: restart the kadmin process
  systemd:
    name: kadmin
    state: restarted
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"  
...
