---
# tasks file for ssl
- name: create workind directory for CA
  file:
    path: "{{ssl.directory.ca}}"
    state: directory
    owner: "{{ssl.directory.user}}"
    group: "{{ssl.directory.group}}"    
    mode: 0550
- stat: path="{{ssl.directory.ca}}/ca-priv-key"
  register: p    
- name: Generate private key and public certifcate for CA
  command: openssl req -new -newkey rsa:4096 -days 365  -x509  -subj '/CN={{ssl.ca.name}}' -keyout "{{ssl.directory.ca}}/ca-priv-key" -out "{{ssl.directory.ca}}/ca-pub-cert" -nodes
  when: not p.stat.exists