---
- template: 
    src: templates/{{blueprint.location}}/blueprint.json.j2
    dest: /root/blueprint.json
    mode: 0755
- template: 
    src: templates/{{blueprint.location}}/template.json.j2
    dest: /root/template.json
    mode: 0755
- name: Download ambari.repo on agent nodes
  get_url:
    url: "{{release.ambari.url}}"
    dest: /etc/yum.repos.d/ambari.repo
    force: yes
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{groups['gateway']|union(groups['agent'])}}"     
- name: Install ambari agents
  yum: name="ambari-agent" state=latest update_cache=yes
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{groups['gateway']|union(groups['agent'])}}"
  when: ansible_facts['os_family'] == "RedHat"    
- name: register ambari-agents  
  replace:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: 'hostname=localhost'
    replace: "hostname={{hostvars[groups['gateway'][0]].ansible_fqdn}}"
    backup: yes
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{groups['gateway']|union(groups['agent'])}}"
- name: start the ambari-agents
  command: ambari-agent restart    
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{groups['gateway']|union(groups['agent'])}}"  
- name: VDF registration
  uri:
    url: "http://{{groups['gateway'][0]}}:8080/api/v1/version_definitions"
    method: POST
    headers:
      X-Requested-By: ambari
    user: admin
    password: admin
    body_format: raw
    body: "{{ lookup('template','templates/version_def.json.j2') | to_json }}" 
    force_basic_auth: yes
    status_code: 201  

- name: register the blueprint
  uri:
    url: "http://{{groups['gateway'][0]}}:8080/api/v1/blueprints/{{cluster.name}}?validate_topology=false"
    method: POST
    headers:
      X-Requested-By: ambari
    user: admin
    password: admin
    body_format: raw
    body: "{{ lookup('template','templates/' + blueprint.location + '/blueprint.json.j2') | to_json }}" 
    force_basic_auth: yes
    status_code: 201  
- name: deploy the blueprint
  uri:
    url: "http://{{groups['gateway'][0]}}:8080/api/v1/clusters/{{cluster.name}}"
    method: POST
    headers:
      X-Requested-By: ambari
    user: admin
    password: admin
    body_format: raw
    body: "{{ lookup('template','templates/' + blueprint.location + '/template.json.j2') | to_json }}" 
    force_basic_auth: yes
    status_code: 202,201  
  tags:
  - justThis    
  
...
