---
# common software installation
- name: Download and set up  python tools
  yum: name="{{ item }}" state=latest update_cache=yes
  when: ansible_facts['os_family'] == "RedHat"
  loop: 
    - python-pip
    - python-wheel 
- name: install pexpect. It is required for interactive command line operations
  pip:
    name: pexpect
    version: 3.3
#- name: install common python modules
#  pip: name="{{ item }}"
#  loop: 
#    - mysqlclient
- name: install NTP for RedHat systems
  yum: name=ntp state=latest update_cache=yes
  when: ansible_facts['os_family'] == "RedHat"
- name: enable service NTP for RedHat systems
  systemd:
    name: ntpd
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"
- name: Download and set up database connectors for RedHat systems
  yum: name="{{ item }}" state=latest update_cache=yes
  when: ansible_facts['os_family'] == "RedHat"
  loop: 
    - mysql-connector-java
    - postgresql-jdbc
    - MySQL-python
- name: install java
  yum: name="{{ item }}" state=latest update_cache=yes
  when: ansible_facts['os_family'] == "RedHat"
  loop: 
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
    - java-1.8.0-openjdk-headless    
- name: configure java home
  lineinfile:
    path: /root/.bashrc
    line: "export JAVA_HOME={{java.home}}"
    insertafter: EOF
- template:
    src: templates/hosts.j2
    dest: /root/hosts
    mode: 0755
- name:  update host mapping in all the nodes
  shell:  cat /root/hosts >> /etc/hosts

- name: Install a kdc client binaries
  yum: name="{{ item }}" state=latest update_cache=yes
  when: ansible_facts['os_family'] == "RedHat"
  loop: 
#    - krb5-auth-dialog
    - krb5-libs
    - krb5-workstation    

- name: provide log directory permissions for all
  file:
    path: "{{item}}"
    state: directory
    mode: 0777
    recurse: yes
  loop: 
    - /var/log
    - /grid/0/log

  
#- name: disable service firewalld 
#  systemd:
#    name: firewalld
#    state: stopped
#    enabled: no

