---
# common software installation
- name: install pexpect. It is required for interactive command line operations
  pip:
    name: pexpect
    version: 3.3
#- name: install common python modules
#  pip: name="{{ item }}"
#  loop: 
#    - mysqlclient
- name: install NTP for RedHat systems
  yum: name=ntp state=latest update_cache=yes
  when: ansible_facts['os_family'] == "RedHat"
- name: enable service NTP for RedHat systems
  systemd:
    name: ntpd
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"
- name: Download and set up database connectors for RedHat systems
  yum: name="{{ item }}" state=latest update_cache=yes
  when: ansible_facts['os_family'] == "RedHat"
  loop: 
    - mysql-connector-java
    - postgresql-jdbc
    - MySQL-python
- name: install java
  yum: name="{{ item }}" state=latest update_cache=yes
  when: ansible_facts['os_family'] == "RedHat"
  loop: 
    - java-1.8.0-openjdk
    - java-1.8.0-openjdk-devel
    - java-1.8.0-openjdk-headless    
- name: configure java home
  lineinfile:
    path: /root/.bashrc
    line: 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk'
    insertafter: EOF
    
#- name: disable service firewalld 
#  systemd:
#    name: firewalld
#    state: stopped
#    enabled: no

