---
# tasks file for database-mysql
- name: install mariadb for RedHat systems
  yum: name="mariadb-server.{{ ansible_architecture }}" state=latest update_cache=yes
  when: ansible_facts['os_family'] == "RedHat"
- name: fix max column size MySQL error
  lineinfile:
    path: /etc/my.cnf
    insertafter: '^ *\[mysqld\] *$' 
    line: '{{item}}'
  loop:
    - innodb_large_prefix = 1
    - innodb_file_per_table = 1
    - innodb_file_format = Barracuda
- name: enable service mariadb for RedHat systems
  systemd:
    name: mariadb
    state: started
    enabled: yes
- name: set password for dba
  mysql_user:
    name: "{{ database.dba.name }}"
    host_all: yes
    state: present
    update_password: always
    password: "{{ database.dba.pswd }}"
    check_implicit_admin: yes
    login_password: "{{ database.dba.pswd }}"
    login_user: "{{ database.dba.name }}"   
- template: 
    src: templates/db-and-users.sql.j2
    dest: /root/db-and-users.sql
    mode: 0755  
- name: create the db and corresponding users
  mysql_db:
    state: import
    name: all
    target: /root/db-and-users.sql  
    login_password: "{{ database.dba.pswd }}"
    login_user: "{{ database.dba.name }}"      
    
