---
- name: cleanup old temporary files
  hosts: 127.0.0.1
  connection: local
  tasks: 
    - file: 
        state: absent
        path: /tmp/ca-pub-cert
- name: configure CA
  hosts: gateway
  roles: 
  - roles/ssl-ca
- name: configure keystores
  hosts: all
  roles: 
  - roles/ssl-keystore  