---
# release related configurations
# for public repos you can get version info from http://public-repo-1.hortonworks.com/HDF/hdf_urlinfo.json / http://public-repo-1.hortonworks.com/HDP/hdp_urlinfo.json
# eg:  "HDF-3.3"["manifests"]["3.0.1.0"]["centos-ppc7"]  ->   3.3.1.0-10 (just version, HDP/HDF should be dropped)
release:
        ambari: 
            url: http://s3.amazonaws.com/dev.hortonworks.com/ambari/centos7/2.x/BUILDS/2.7.3.0-142/ambaribn.repo
        hdf:
            url:  http://s3.amazonaws.com/dev.hortonworks.com/HDF/centos7/3.x/BUILDS/3.3.2.0-9/hdfbn.repo
            #mpack: http://public-repo-1.hortonworks.com/HDF/centos7/3.x/updates/3.3.1.0/tars/hdf_ambari_mp/hdf-ambari-mpack-3.3.1.0-10.tar.gz
            mpack: http://s3.amazonaws.com/dev.hortonworks.com/HDF/centos7/3.x/BUILDS/3.3.2.0-9/tars/hdf_ambari_mp/hdf-ambari-mpack-3.3.2.0-9.tar.gz
            install: yes 
            purge: no 
            version: 3.3.2.0-9
        hdp:
            url:    http://s3.amazonaws.com/dev.hortonworks.com/HDP/centos7/3.x/BUILDS/3.1.0.0-78/hdpbn.repo
            version: 3.1.0.0-78
            #url:  http://public-repo-1.hortonworks.com/HDP/centos7/3.x/updates/3.0.1.0/hdp.repo
            #version: 3.0.1.0-187
        hdp_gpl:
            base_url: http://public-repo-1.hortonworks.com/HDP-GPL/centos7/3.x/updates/3.1.0.0
            version: HDP-3.1-GPL
        hdp_utils:
            base_url: http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.22/repos/centos7
            version: HDP-UTILS-1.1.0.22

# cluster properties            
cluster:
    name: cl1
    security:
        kerberos: yes
        ssl: yes
    os: redhat7

# blueprint configurations
blueprint:
    #location: hdp310_hdf330_static_01
    #location: hdp_310_static_01    
    location: hdp310_hdf330_static_02   
    #location: hdp_310_static_02  

# java-configurations
# ibm-cloud  java_home:  /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.ppc64le
# ycloud java_home:  /usr/lib/jvm/java-1.8.0-openjdk
java:
    home:  /usr/lib/jvm/java-1.8.0-openjdk


# database configurations
database:
        dbflavour: mysql
        dba:
           name: root
           pswd: passW0rd
        users:
             ambari:
                   name: ambari
                   pswd: bigdata
             streamline:
                   name: streamline
                   pswd: streamline
             registry:
                   name: registry
                   pswd: registry
             ranger:
                   name: rangerdba
                   pswd: rangerdba
             druid:
                   name: druid
                   pswd: druid
             superset:
                   name: superset
                   pswd: superset
             hivedb:       
                   name: hive
                   pswd: hive



# security-kerberos configurations, effective if cluster.security.kerberos = yes
kerberos:
    enable: yes
    realm: HDF.COM
    db_master_key: passW0rd
    admin_princ_pswd: passW0rd

ssl:
    storepswd: passW0rd
    keypswd: passW0rd
    directory: 
      ca: /grid/0/kafka-security/ca
      store: /grid/0/kafka-security/store
      group: hadoop
      user: kafka 
    ca:
      name: QA-Security-CA
      
...
