---
dbflavour: mysql
dba:
    name: root
    pswd: passW0rd
users:
    ambari:
      name: ambari
      pswd: bigdata
    streamline:
      name: streamline  
      pswd: streamline
    registry:
      name: registry  
      pswd: registry
    rangerdba:
      name: rangerdba  
      pswd: rangerdba 
    druid:     
      name: druid  
      pswd: druid 
    superset:
      name: superset  
      pswd: superset       
